### ISSUE TITLE
Not able to read two motes

### ISSUE THREAD

**Issue by dserbu** [eduarias/iot_fog#1]
If in the config.yml file is added another mote than an error will be prometed.

devices:
  read_interval: 5
  mote01:
    name: mote01
    ipv6: bbbb::12:4b00:0615:aaaa
  mote02:
    name: mote02
    ipv6: bbbb::12:4b00:0615:aaab

socket.error: [Errno 98] Address already in use

**Comment by eduarias** [comment]
Unfortunately I don't have any mote device right now, so I cannot debug this behavior. Please attach some logs with more details and I'll try to help.

**Comment by eduarias** [comment]
@dserbu Please try branch  `#1_not_able_to_read_two_motes` to see if it fix the issue.

**Comment by dserbu** [comment]
@eduarias Yes the new branch almost solved the issue. The problem now is that in **get_data()** I call all the resources, which means that a resource that doesn't exist for an ip adress will be called.
What I did to solve the new problem is to add an if condition, but maybe you have a more elegant way to do it.
`def get_data(self):
		if self.name =='mote01':
			res={'temperature': self.get_temperature(),'humidity': self.get_humidity(),}
		else:
			res={ 'light': self.get_light(),}
		
		return res`
Thanks you for your fast answer.

**Comment by dserbu** [comment]
I will make the second option. Thank you for your help, you can mark the issue as solved.
